kind: Simple
apiVersion: k3d.io/v1alpha2
name: my-cluster
image: rancher/k3s:v1.31.1-k3s1
servers: 1
agents: 0
ports:
  - port: 6443:6443
    nodeFilters:
      - server:0
  - port: 80:80
    nodeFilters:
      - server:0
options:
  k3s:
    extraServerArgs:
      - --tls-san=192.168.1.87
      # - --no-deploy=traefik